
const swearWords = [
    "feck",
    "fuck",
    "shit",
    "bitch",
    "cunt",
    "arse",
    "ass",
    "bastard",
    "tf",
    "nigga",
    "nigger",
    "wtf",
    "whore",
    "dick",
    "dildo",
    "penis",
    "cock",
    "balls",
    "bust",
    "cum", 
    "pussy",
    "arse",
    "arsehole",
    "ass",
    "asshole",
    "balls",
    "bastard",
    "beaver",
    "beef curtains",
    "bellend",
    "bint",
    "bloodclaat",
    "bloody",
    "bollocks",
    "bugger",
    "bullshit",
    "child-fucker",
    "christ on a bike",
    "christ on a cracker",
    "clunge",
    "cock",
    "cow",
    "crap",
    "cunt",
    "damn",
    "dick",
    "dickhead",
    "effing",
    "fanny",
    "feck",
    "flaps",
    "frigger",
    "fuck",
    "gash",
    "ginger",
    "git",
    "god",
    "goddam",
    "goddamn",
    "godsdamn",
    "hell",
    "holy shit",
    "horseshit",
    "jesus christ",
    "jesus fuck",
    "jesus h. christ",
    "jesus harold christ",
    "jesus wept",
    "jesus, mary and joseph",
    "judas priest",
    "knob",
    "minge",
    "minger",
    "motherfucker",
    "munter",
    "nigga",
    "pissed",
    "pissed off",
    "prick",
    "punani",
    "pussy",
    "shit ass",
    "shitass",
    "slut",
    "snatch",
    "sod",
    "sod-off",
    "son of a bitch",
    "son of a whore",
    "sweet jesus",
    "tit",
    "tits",
    "twat",
    "wanker"
];

export default swearWords;